## cahcematrix.R -- Build cache which contains the inverse of input matrix 
## so to limit calls to Solve() function to only when matrix is changed; thereby
## increasing computational performance.
## First, make call to makeCacheMatrix(x); where x is matrix to inverse
## makeCacheMatrix returns a list of functions which will be use by cacheSolve().
## thereafter call cacheSolve(x); where input parameter x is the return list generated by makeCacheMatrix.

## makeCacheMatrix input argument is a matrix.  Return is a list of functions 
## to (set, get, setinverse, getinverse)

makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) { ## sets the matrix values 
            x <<- y
            i <<- NULL  ##initial matrix inverse is set to NULL
    }
    get <- function() x ## get back the value of x
    setinverse <- function(inverse) i <<- inverse ##set the value of inverse
    getinverse<- function() i ## get the value of inverse
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## cacheSolve takes as input a special vector of functions created by makeCacheMatrix
## to set, get, setinverse, getinverse.
## The function are used to determine if the matrix has been changed.
## If the matrix has been unchanged, then the inverse matrix stored is returned
## else the solve function is called to inverse the new matrix.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    i <- x$getinverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinverse(i)
}
